server:
    port: 8088

logging:
    level:
        com.flyimg.dao: debug

spring:
    datasource:
        url: jdbc:mysql://47.114.110.66:3306/mktdesk_oss?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
        username: mktdesk_oss
        password: mkt_202003
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 300
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
    redis:
        host: 127.0.0.1
        port: 6379
        password:
        timeout: 7000
        database: 1
        lettuce:
            pool:
                max-wait: 100
                max-active: 200
                max-idle: 10
                min-idle: -1

mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    global-config:
        id-type: 2
        field-strategy: 1
        db-column-underline: true
        refresh-mapper: true
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: false

#以下为框架业务配置 ==================================
defalutHost: testimg.lfscrm.com