
server:
    max-http-header-size: 4048576
    tomcat:
        basedir: /data/upload_tmp
        connection-timeout: 30000
        max-http-form-post-size: -1
        threads:
            max: 1000


spring:
    profiles:
        active: dev
    cache:
        type: caffeine
        caffeine:
            spec: initialCapacity=10,maximumSize=200,expireAfterWrite=300s #,refreshAfterWrite=10s
        cache-names: user #可以用,号分割多个
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss

mybatis:
    mapper-locations: classpath:mapper/*.xml
    global-config:
        id-type: 2
        field-strategy: 1
        db-column-underline: true
        refresh-mapper: true
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: false


Expression: 0 30 04 * * ?

systemupdate: '2019-11-29'

#以下为框架业务配置 ==================================
defalutHost: 127.0.0.1
writeDirectory: /flyimgfile/